//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemDetail
    {
        public int DetailID { get; set; }
        public int SubID { get; set; }
        public int ReceviedID { get; set; }
        public decimal Cost { get; set; }
    
        public virtual CustomerReceipt CustomerReceipt { get; set; }
        public virtual SubProblem SubProblem { get; set; }
    }
}
