//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceCenterSystemEntities : DbContext
    {
        public ServiceCenterSystemEntities()
            : base("name=ServiceCenterSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<CustomerReceipt> CustomerReceipts { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<ProblemDetail> ProblemDetails { get; set; }
        public virtual DbSet<SubProblem> SubProblems { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
